import type { ComponentType } from 'react'
import {
  CatIllustration,
  CowIllustration,
  DogIllustration,
  DuckIllustration,
  ElephantIllustration,
  FrogIllustration,
  HorseIllustration,
  LionIllustration,
  PigIllustration,
  SheepIllustration,
  type IllustrationProps,
} from './Animals'
import {
  AppleIllustration,
  BananaIllustration,
  BroccoliIllustration,
  CarrotIllustration,
  CornIllustration,
  GrapesIllustration,
  OrangeIllustration,
  StrawberryIllustration,
  TomatoIllustration,
  WatermelonIllustration,
} from './Fruits'
import {
  CircleIllustration,
  DiamondIllustration,
  HeartIllustration,
  OvalIllustration,
  RectangleIllustration,
  SquareIllustration,
  StarIllustration,
  TriangleIllustration,
} from './Shapes'
import {
  AirplaneIllustration,
  BusIllustration,
  CarIllustration,
  FireTruckIllustration,
  HelicopterIllustration,
  PoliceCarIllustration,
  TrainIllustration,
  TruckIllustration,
} from './Vehicles'

/** PackItem.image keys resolve here; pack data stays plain strings. */
export const illustrations: Record<string, ComponentType<IllustrationProps>> = {
  cow: CowIllustration,
  dog: DogIllustration,
  cat: CatIllustration,
  duck: DuckIllustration,
  sheep: SheepIllustration,
  pig: PigIllustration,
  horse: HorseIllustration,
  frog: FrogIllustration,
  lion: LionIllustration,
  elephant: ElephantIllustration,
  apple: AppleIllustration,
  banana: BananaIllustration,
  orange: OrangeIllustration,
  strawberry: StrawberryIllustration,
  grapes: GrapesIllustration,
  watermelon: WatermelonIllustration,
  carrot: CarrotIllustration,
  tomato: TomatoIllustration,
  broccoli: BroccoliIllustration,
  corn: CornIllustration,
  circle: CircleIllustration,
  square: SquareIllustration,
  triangle: TriangleIllustration,
  star: StarIllustration,
  heart: HeartIllustration,
  diamond: DiamondIllustration,
  oval: OvalIllustration,
  rectangle: RectangleIllustration,
  car: CarIllustration,
  truck: TruckIllustration,
  bus: BusIllustration,
  airplane: AirplaneIllustration,
  train: TrainIllustration,
  'fire-truck': FireTruckIllustration,
  'police-car': PoliceCarIllustration,
  helicopter: HelicopterIllustration,
}
