// Generates PWA icons and iOS splash screens from the Boop mascot SVG.
// Run: node scripts/generate-assets.mjs   (outputs are committed in public/)
import sharp from 'sharp'
import { mkdir } from 'node:fs/promises'

const CREAM = '#FFF8ED'
const SUNSHINE = '#FFD23F'

const MASCOT = `
  <circle cx="100" cy="105" r="80" fill="#FFD23F" stroke="#2D2A32" stroke-width="10"/>
  <ellipse cx="72" cy="92" rx="13" ry="17" fill="#2D2A32"/>
  <ellipse cx="128" cy="92" rx="13" ry="17" fill="#2D2A32"/>
  <circle cx="76" cy="86" r="4.5" fill="#FFF8ED"/>
  <circle cx="132" cy="86" r="4.5" fill="#FFF8ED"/>
  <path d="M78 128 Q100 148 122 128" fill="none" stroke="#2D2A32" stroke-width="9" stroke-linecap="round"/>
  <circle cx="52" cy="120" r="11" fill="#FF6B6B" opacity="0.55"/>
  <circle cx="148" cy="120" r="11" fill="#FF6B6B" opacity="0.55"/>`

/** Mascot on a solid square, sized so the face fills `scale` of the canvas. */
function iconSvg(size, bg, scale) {
  const m = (size * scale) / 200
  const offset = (size - 200 * m) / 2
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}">
       <rect width="${size}" height="${size}" fill="${bg}"/>
       <g transform="translate(${offset} ${offset}) scale(${m})">${MASCOT}</g>
     </svg>`,
  )
}

function splashSvg(w, h) {
  const m = (Math.min(w, h) * 0.28) / 200
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
       <rect width="${w}" height="${h}" fill="${CREAM}"/>
       <g transform="translate(${(w - 200 * m) / 2} ${(h - 200 * m) / 2}) scale(${m})">${MASCOT}</g>
     </svg>`,
  )
}

await mkdir('public/icons', { recursive: true })
await mkdir('public/splash', { recursive: true })

const icons = [
  ['public/icons/icon-192.png', iconSvg(192, CREAM, 0.86)],
  ['public/icons/icon-512.png', iconSvg(512, CREAM, 0.86)],
  ['public/icons/icon-maskable-512.png', iconSvg(512, SUNSHINE, 0.62)],
  ['public/icons/apple-touch-icon.png', iconSvg(180, CREAM, 0.86)],
]
for (const [path, svg] of icons) {
  await sharp(svg).png().toFile(path)
  console.log(path)
}

// Portrait pixel sizes; landscape is generated by swapping. Keys are CSS
// device-width x device-height @ dpr for the apple-touch-startup-image media
// queries in index.html.
const SPLASH = [
  [2064, 2752], // iPad Pro 13 M4    @2  1032x1376
  [2048, 2732], // iPad Pro 12.9     @2  1024x1366
  [1668, 2420], // iPad Pro 11 M4    @2  834x1210
  [1668, 2388], // iPad Pro 11       @2  834x1194
  [1668, 2224], // iPad Pro 10.5/Air3 @2 834x1112
  [1640, 2360], // iPad Air 10.9     @2  820x1180
  [1620, 2160], // iPad 10.2         @2  810x1080
  [1536, 2048], // iPad 9.7/mini 5   @2  768x1024
  [1488, 2266], // iPad mini 6/7     @2  744x1133
  [1320, 2868], // iPhone 16 Pro Max @3  440x956
  [1290, 2796], // iPhone Pro Max    @3  430x932
  [1206, 2622], // iPhone 16 Pro     @3  402x874
  [1179, 2556], // iPhone 14/15 Pro  @3  393x852
  [1170, 2532], // iPhone 12-14      @3  390x844
  [828, 1792], //  iPhone XR/11      @2  414x896
]
for (const [w, h] of SPLASH) {
  await sharp(splashSvg(w, h)).png().toFile(`public/splash/splash-${w}x${h}.png`)
  await sharp(splashSvg(h, w)).png().toFile(`public/splash/splash-${h}x${w}.png`)
  console.log(`splash ${w}x${h} + landscape`)
}
